### ISSUE TITLE
Spark assumes unlink is in /bin

### ISSUE THREAD

**Issue by plietar** [NorfairKing/super-user-spark#10]
On OS X (at least) it is in `/usr/bin/unlink`
Why is it even required ? Can't you just use `rmFile` ?

**Comment by NorfairKing** [comment]
I think rmFile will remove the file that the link points to.
Feel free to try it out and send a pull-request.

**Comment by plietar** [comment]
`rmFile` uses `System.removeFile`.
The documentation is unclear, but `System.removeFile` (on POSIX) calls `Posix.Files.removeLink`, which uses `unlink(3)`, which according to the man page only removes the symlink, not the target :smile:

**Comment by NorfairKing** [comment]
If I make a pull-request with a fix, will you try it out and tell me whether that fixes the problem for you?
