### ISSUE TITLE
Support for autodiscovery of dotfiles in directory?

### ISSUE THREAD

**Issue by samis** [NorfairKing/super-user-spark#14]
Using tools like GNU stow, it is possible to link directories and such without specifying the exact file names. This is very useful for managing dotfiles as it is easier to use and in some cases it can be tedius to explicitly state each file to be linked. Does this method of managing dotfiles offer similar functionality?

**Comment by NorfairKing** [comment]
It's not exactly clear what you mean.
It's possible to deploy entire directories using the exact same syntax:

```
card direxample {
  file -> file_deployed
  directory -> directory_deployed
}
```

If that's not what you meant, make sure to have a look at [the open project suggestion for the super user charger](http://cs-syd.eu/projects/suggestions/super-user-charger.html) and tell me what you think.

**Comment by samis** [comment]
The super-user charger indeed looks very interesting. I currently use my own tool for management of dotfiles, but it shares the limitations of stow and additional limitations from design choices. This tool looks very interesting and I may end up converting to it (or a wrapper around it). I'll close this now.
