### ISSUE TITLE
Can't install sus with cabal

### ISSUE THREAD

**Issue by NWuensche** [NorfairKing/super-user-spark#21]
Hi,

when I try to `cabal install super-user-spark`, I just get

[25 of 26] Compiling Arguments        ( src/Arguments.hs, dist/build/Arguments.o )

src/Arguments.hs:60:21:

    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:77:60:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:79:13:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:86:25:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:88:13:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:95:26:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:97:13:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:104:25:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:106:13:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:113:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:114:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:115:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:116:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:119:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:120:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:121:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:122:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:125:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:126:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:127:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:128:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:131:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:134:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:137:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:140:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:141:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)

src/Arguments.hs:144:9:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)
cabal: Error: some packages failed to install:
super-user-spark-0.3.2.0 failed during the building phase. The exception was:
ExitFailure 1

What should I do?

**Comment by NorfairKing** [comment]
This means I made a mistake in the bounds of this package.

Try `stack install super-user-spark` instead, until I can fix this problem (which may not be any time soon, due to time contstraints)

**Comment by stites** [comment]
It is weird that it isn't finding `<>` which should come from the Data.Monoid import. It's possible that you are either on a very old version of GHC (unlikely given the min-base version requirement), or you need to update your version of optparse-applicative.

If you are just installing stack now, you might run into trouble globally installing. In that case, pull down this repo and `stack install` from the project root, if you still hit a bump with the GHC version (like I did) checkout #22 and stack install again with a different lts.
