### ISSUE TITLE
super-user-spark-0.2.0.1 can't build its test suite

### ISSUE THREAD

**Issue by peti** [NorfairKing/super-user-spark#8]
Citing from http://hydra.cryp.to/build/1306687/nixlog/2/raw:

~~~
Preprocessing test suite 'spark-tests' for super-user-spark-0.2.0.1...

test/TestMain.hs:4:26:
    Could not find module ‘Parser.Test’
    Use -v to see a list of the files searched for.

test/TestMain.hs:5:26:
    Could not find module ‘Compiler.Test’
    Use -v to see a list of the files searched for.
~~~~

These files appear to be missing from the release tarball.

**Comment by NorfairKing** [comment]
This should now be solved. Could you check and keep me up to date?

**Comment by peti** [comment]
If you release a new version to Hackage, then our CI will test it automatically within an hour at http://hydra.cryp.to/job/nixpkgs/haskell-updates/haskellPackages.super-user-spark.x86_64-linux/all.

**Comment by NorfairKing** [comment]
Looks like it's working. Thank you for raising this issue!
