### ISSUE TITLE
git usage

### ISSUE THREAD

**Issue by iharh** [NorfairKing/super-user-spark#9]
Hello.
Could you show the sample of using git for extracting spark cards (say, from github repos).
I can see keywordGit declared at Constants.hs, but there seems to be no any usage of it.

**Comment by NorfairKing** [comment]
I dropped support for direct git sparking because:
1. Spark would clone the repository anyway.
2. The user will probably want to have their dotfiles locally anyway.

TL;DR Just clone the repository and `spark deploy yoursparkcardfilehere.sus`.

**Comment by iharh** [comment]
Thank you, Norfair. Will try to go that way.
